
IF(${CMAKE_C_COMPILER} MATCHES "gcc")
	SET(C_IS_GNU   1)
ENDIF()
IF(${CMAKE_C_COMPILER} MATCHES "icc")
	SET(C_IS_INTEL 1)
ENDIF()
IF(${CMAKE_C_COMPILER} MATCHES "cl")
	SET(C_IS_MSVC  1)
ENDIF()
IF(${CMAKE_C_COMPILER} MATCHES "cc")
	SET(C_IS_SUN  1)
ENDIF()

